### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by JustJoostNL** [node-libraries/prisma-accelerate-local#1]
Hey there! Really like the library you made!

I just setup my selfhosted accelerate, but can't get it to work. Could you give me a client side example code?

Thanks in advance. :)

**Comment by SoraKumo001** [comment]
@JustJoostNL 
We have placed a sample at the following URL

https://github.com/SoraKumo001/prisma-accelerate-local-test

**Comment by JustJoostNL** [comment]
Thanks!
